# Generated by Django 3.0.6 on 2020-07-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myItemName', models.CharField(max_length=200)),
                ('myItemStore', models.CharField(max_length=200)),
                ('myItemDate', models.DateTimeField(verbose_name='date published')),
                ('myItemCat', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-myItemDate'],
            },
        ),
    ]
