# Generated by Django 3.0.6 on 2020-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipTitle', models.CharField(max_length=200)),
                ('tipDate', models.DateField(verbose_name='date published')),
                ('tipBody', models.TextField()),
                ('tipImg', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
