# Generated by Django 3.0.8 on 2020-07-30 06:38

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0002_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200, null=True)),
                ('itemDetail', models.CharField(max_length=400, null=True)),
                ('itemPrice', models.CharField(max_length=20, null=True)),
                ('itemImg', imagekit.models.fields.ProcessedImageField(upload_to='images/')),
                ('itemStore', models.CharField(max_length=50, null=True)),
                ('itemLink', models.CharField(max_length=500, null=True)),
                ('itemShip', models.CharField(max_length=20, null=True)),
                ('itemCat', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
