# Generated by Django 3.0.8 on 2020-08-06 06:04

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0004_auto_20200806_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemDetail1',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemImg1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemLink1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemPrice1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemShip1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemStore1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
